### ISSUE TITLE
Problem with CORS authorisation headers

### ISSUE THREAD

**Issue by Opteract** [JasonLovesDoggo/abacus#2]
Dear Mr. Cameron, 
I recently found your Abacus API and it is exactly what i need for my small web-game project.
The project is in Javascript/HTML and it tries to call the
```javascript
 /update/:namespace/*key?value=:amount
``` 
endpoint in the backround to keep track of some scores.

Unfortunately every time i try to programmatically call this endpoint, i get an error in the web-console, saying that the **CORS** header did not include a header allowing the _**Authorization**_  header in my request.
I dug deeper and i could not find any fixes on my end but to disable my browser security, but that is not a persisting fix.
I found that the server has to return the following header to allow the request:
```javascript
Access-Control-Allow-Headers: Authorization
``` 
I would really appreciate if you could take a look at this and i am happy to provide more info if needed.

Sincerely,
S.Z.

**Comment by JasonLovesDoggo** [comment]
Hey! Thanks for the issue, I'll check it out tonight and should have a patch out then!

**Comment by JasonLovesDoggo** [comment]
Let me know if you still have issues, prod is updated!

**Comment by Opteract** [comment]
It seems to work perfectly!
Thank you for your time and efforts!

Sincerely,
S.Z.

**Comment by JasonLovesDoggo** [comment]
> It seems to work perfectly! Thank you for your time and efforts!
> 
> Sincerely, S.Z.

Glad to hear it!

If you ever have any feedback in the future on how I can improve abacus, just let me know!
