### ISSUE TITLE
Option to increment the counter only with the token.

### ISSUE THREAD

**Issue by RafaelBomfim128** [JasonLovesDoggo/abacus#3]
Currently, I have an issue where I have a serverless application that requires a counter, but I don’t want other people to have access to it to prevent sabotage. I need to "hide" the URL somehow, but since my application is serverless, I can’t create a small backend with Express to act as an intermediary for the call to Abacus. The idea is to have some kind of counter that can only be modified through a token (e.g., admin_key), which would be hidden in the environment variables of my site and called every time I need to increment the counter.

**Comment by JasonLovesDoggo** [comment]
> Currently, I have an issue where I have a serverless application that requires a counter, but I don’t want other people to have access to it to prevent sabotage. I need to "hide" the URL somehow, but since my application is serverless, I can’t create a small backend with Express to act as an intermediary for the call to Abacus. The idea is to have some kind of counter that can only be modified through a token (e.g., admin_key), which would be hidden in the environment variables of my site and called every time I need to increment the counter.

So you are essentially saying to add a flag to disable /hit on token creation? 

Because currently All of the other modification endpoints are locked behind the admin_key which only you would have

**Comment by JasonLovesDoggo** [comment]
> Currently, I have an issue where I have a serverless application that requires a counter, but I don’t want other people to have access to it to prevent sabotage. I need to "hide" the URL somehow, but since my application is serverless, I can’t create a small backend with Express to act as an intermediary for the call to Abacus. The idea is to have some kind of counter that can only be modified through a token (e.g., admin_key), which would be hidden in the environment variables of my site and called every time I need to increment the counter.

So you are essentially saying to add a flag to disable /hit on token creation? 

Because currently All of the other modification endpoints are locked behind the admin_key which only you would have

**Comment by RafaelBomfim128** [comment]
> So you are essentially saying to add a flag to disable /hit on token creation?
> 
> Because currently All of the other modification endpoints are locked behind the admin_key which only you would have

First of all, thank you for the quick response! Actually, the idea was to create a type of counter that does not allow a 'hit' without a token, so that only my application can modify it, without the risk of other people intercepting my endpoint through the Network tab of the Developer Tools and sabotaging my counter.

If this moves forward to real development, I don't think we should do this by modifying the current 'hit', as it could impact many applications, but rather by adding a new counter mode (perhaps an additional parameter in the 'create') that does not accept any modifications without a token.

Either way, I'm implementing a backend in my application, so I can work around this by hiding the original URL and creating a redirector through Node's 'express', so it becomes an optional development, I appreciate the willingness and feel free to accept the idea or close the topic.

**Comment by RafaelBomfim128** [comment]
> Sorry for the confusion but that's actually what I was saying as well.
> 
> The way you're doing that currently seems to be an easier solution. However, you'll want to keep in mind that if this token that you're talking about is running client side, then they would still be able to access it. And as for your solution, you would still have to have some kind of system only authentication.
> 
> But if you are interested in this future in the future just let me know or feel free to make a pull request for it.

Thank you for the warning, I'm still a beginner in development and I'm trying to figure out a way to ensure that my token is not exposed on the client side. Basically, I want to keep my counter fully protected against writes that don't come from my site (like, for example, a script in Postman). For now, I'll keep researching, and I appreciate your attention!
